# MULTIPLE REGRESSION

In [40]:
import pandas as pd 
import numpy as np 

In [16]:
data = pd.read_csv("Iris.csv")

In [17]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [31]:
X = data.iloc[:,1:4]
ones = np.ones([X.shape[0],1])
X = np.concatenate((ones,X),axis = 1)
df = pd.DataFrame(data=data, columns=['y', 'dummy', 'x'])
just_dummies = pd.get_dummies(df['dummy'])
#dummies = pd.get_dummies(df['Iris-setosa'])

In [19]:
Y = data.iloc[:,2:3].values

In [33]:
W = np.zeros([1,4])

In [32]:
print(X)

[[1.  5.1 3.5 1.4]
 [1.  4.9 3.  1.4]
 [1.  4.7 3.2 1.3]
 [1.  4.6 3.1 1.5]
 [1.  5.  3.6 1.4]
 [1.  5.4 3.9 1.7]
 [1.  4.6 3.4 1.4]
 [1.  5.  3.4 1.5]
 [1.  4.4 2.9 1.4]
 [1.  4.9 3.1 1.5]
 [1.  5.4 3.7 1.5]
 [1.  4.8 3.4 1.6]
 [1.  4.8 3.  1.4]
 [1.  4.3 3.  1.1]
 [1.  5.8 4.  1.2]
 [1.  5.7 4.4 1.5]
 [1.  5.4 3.9 1.3]
 [1.  5.1 3.5 1.4]
 [1.  5.7 3.8 1.7]
 [1.  5.1 3.8 1.5]
 [1.  5.4 3.4 1.7]
 [1.  5.1 3.7 1.5]
 [1.  4.6 3.6 1. ]
 [1.  5.1 3.3 1.7]
 [1.  4.8 3.4 1.9]
 [1.  5.  3.  1.6]
 [1.  5.  3.4 1.6]
 [1.  5.2 3.5 1.5]
 [1.  5.2 3.4 1.4]
 [1.  4.7 3.2 1.6]
 [1.  4.8 3.1 1.6]
 [1.  5.4 3.4 1.5]
 [1.  5.2 4.1 1.5]
 [1.  5.5 4.2 1.4]
 [1.  4.9 3.1 1.5]
 [1.  5.  3.2 1.2]
 [1.  5.5 3.5 1.3]
 [1.  4.9 3.1 1.5]
 [1.  4.4 3.  1.3]
 [1.  5.1 3.4 1.5]
 [1.  5.  3.5 1.3]
 [1.  4.5 2.3 1.3]
 [1.  4.4 3.2 1.3]
 [1.  5.  3.5 1.6]
 [1.  5.1 3.8 1.9]
 [1.  4.8 3.  1.4]
 [1.  5.1 3.8 1.6]
 [1.  4.6 3.2 1.4]
 [1.  5.3 3.7 1.5]
 [1.  5.  3.3 1.4]
 [1.  7.  3.2 4.7]
 [1.  6.4 3.2 4.5]
 [1.  6.9 3.

In [35]:
print(W)

[[0. 0. 0. 0.]]


In [57]:
alpha = 0.01
iterations = 1000

In [58]:
def Cost_Func(X,Y,W):
    MSE = np.power(((X @ W.T)-Y),2)
    return np.sum(MSE)/(2 * len(X))

In [59]:
def gradientDescent(X,Y,W,iterations,alpha):
    cost = np.zeros(iterations)
    for i in range(iterations):
        W = W - (alpha/len(X)) * np.sum(X * (X @ W.T - Y), axis=0)
        cost[i] = Cost_Func(X, Y, W)
    
    return W,cost

In [61]:
Weights,Cost = gradientDescent(X,Y,W,iterations,alpha)
print(Weights)
min_cost = Cost_Func(X,Y,Weights)
print(min_cost) 

[[ 0.08894048  0.22467007  0.69913507 -0.12796268]]
0.00492296904122135
